### ISSUE TITLE
ConfiguracaoPreferenciaActivity

### ISSUE THREAD

**Issue by gesuvs** [GBernardo10/Borapp#4]
### Bug na tela de preferencias
![Screenshot_20200529_004627](https://user-images.githubusercontent.com/42353858/83219139-f3018580-a145-11ea-9b48-83f4ab95f331.png)

![Screenshot_20200529_004843](https://user-images.githubusercontent.com/42353858/83219208-26dcab00-a146-11ea-9048-ea8405b7b5bf.png)

**Comment by tjambeiro** [comment]
O problema acontece quando abre a tela de preferências?
